### ISSUE TITLE
Bouwen van kaartjes voor de contourings

### ISSUE THREAD

**Issue by zoepje** [Ryank2004/Oncollaboration-Sprint-14#14]
Hierbij behoord ook het dynamisch maken van de data die in de kaartjes komen te staan. 
![Image](https://github.com/user-attachments/assets/b3be40c9-086d-415e-bc3e-5c046867fb75)

**Comment by DamianR2004** [comment]
Voor het bouwen van de kaartjes van de CT-scans heb ik geen vernieuwd design gemaakt, dit omdat het al voor ons klaarlag.

# Ontwerpen

## Breakdownschets


# Bouwen

## Data ophalen uit de directus database

Het ophalen van de data voor de webinars en de CT-scans is dit stukje code gebruikt:

https://github.com/Ryank2004/Oncollaboration-Sprint-14/blob/b8c26ad8f4433e98c711f62b2571047391e0f515/src/routes/%2Blayout.server.js#L1-L16

Eerst is de link gekoppeld end daarna zijn de verschillende images, titels, categorieën en andere dingen uit de database gehaald. Door het gebruiken van fields is het mogelijk om dit te doen met many to many tabellen.  


## HTML 

Qua html niet heel veel bijzonders. Ik heb gebruik gemaakt van een article met headers, images en een span element. Er is nog gebruik gemaakt van een standaard width en height. Hiermee voorkom je layout shifts op je pagina. 

https://github.com/Ryank2004/Oncollaboration-Sprint-14/blob/b8c26ad8f4433e98c711f62b2571047391e0f515/src/lib/contouring-overview.svelte#L9-L20


## CSS

Qua CSS ook geen hele gekke dingen. De kaartjes zijn goed responsive en zien er hetzelfde uit als het aangeleverde design die we hebben gekregen. Ook is er gebruik gemaakt van custom-properties. Dit is erg fijn omdat we alle fonts, borders en de kleuren consistent kunnen houden over de hele webiste.

https://github.com/Ryank2004/Oncollaboration-Sprint-14/blob/b8c26ad8f4433e98c711f62b2571047391e0f515/src/lib/contouring-overview.svelte#L70-L83
