### ISSUE TITLE
Justus code review

### ISSUE THREAD

**Issue by Ryank2004** [Ryank2004/Oncollaboration-Sprint-14#57]
Static folder netter indelen
assets kan css en meer in

hoofdletter bij componenten en geen streepjes.
 index.js gebruiken voor verzameling componenten.

svelte genereert zelf classes dus minder onnodige classes gebruiken bij componenten.

alt teksten bij contouren component

labels in filter kan een component zijn

atomicdesign van brad frost

... = spread operator

**Comment by zoepje** [comment]
- [x] static folder beter indelen
- [ ] atomicdesign als we dat willen
- [ ] hoofdletter bij componenten en geen streepjes. Hier gaat iets fout met vercel.
